name: 'Rum & Zigarre'
favicon: null
layout_spectrum: 0.9079287955537438
typography_spectrum: 0.7347040455788374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.34283091593533754
  lightness: 0.5403456655330956
  saturation: 0.8058529500849545
  rhythmicContrast: 0.3959650592878461
purpose: []
